version: 0.2

env:
  variables:
    LAMBDA_FUNC_NAME: "hello_lambda"
    LAMBDA_ENV_VARIABLE: "FEATURE_ENABLED"
    LAMBDA_ENV_VARIABLE_VALUE: "true"

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
      - echo "Packaging Lambda..."
      - zip -r lambda_package.zip main.py

  post_build:
    commands:
      - echo "更新 Lambda 原始碼..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNC_NAME --zip-file fileb://lambda_package.zip
      - echo "發佈新版本..."
      - sleep 10
      - VERSION=$(aws lambda publish-version --function-name $LAMBDA_FUNC_NAME --query 'Version' --output text)
      - echo "發佈版本為:$VERSION"
      - echo "更新 alias $LAMBDA_ALIAS_NAME 指向版本 $VERSION"
      - sleep 10
      - aws lambda update-alias --function-name $LAMBDA_FUNC_NAME --name $LAMBDA_ALIAS_NAME --function-version $VERSION

#artifacts:
#  files:
#    - lambda_package.zip

#logs:
#  cloudwatch:
#    enabled: true
