version: 0.2

env:
  variables:
    LAMBDA_FUNC_NAME: "hello_lambda"
    LAMBDA_ENV_VARIABLE: "FEATURE_ENABLED"
    LAMBDA_ENV_VARIABLE_VALUE: "true"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "安裝依賴..."
      - pip install -r requirements.txt -t .
      - echo "安裝完成！"

  build:
    commands:
      - echo "打包 Lambda..."
      - zip -r lambda_package.zip main.py

  post_build:
    commands:
      - echo "部署準備完成，交由 CodePipeline Deploy 階段處理"
#      - echo "部署 Lambda 到 AWS..."
#      - aws lambda update-function-code --function-name $LAMBDA_FUNC_NAME --zip-file fileb://lambda_package.zip
#      - echo "部署完成！"

artifacts:
  files:
    - lambda_package.zip

#logs:
#  cloudwatch:
#    enabled: true