version: 0.2

env:
  variables:
    LAMBDA_FUNC_NAME: "hello_lambda"
    LAMBDA_ENV_VARIABLE: "FEATURE_ENABLED"
    LAMBDA_ENV_VARIABLE_VALUE: "true"

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
      - echo "Packaging Lambda..."
      - zip -r lambda_package.zip main.py

  post_build:
    commands:
      - echo "部署 Lambda 到 AWS..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNC_NAME --zip-file fileb://lambda_package.zip
      - echo "部署完成！"

#artifacts:
#  files:
#    - lambda_package.zip

#logs:
#  cloudwatch:
#    enabled: true